apt_extra_packages:
  - libasound2-dev
  - libasound2-plugins
  - libportaudio2
  - ffmpeg
  - nvidia-settings

install_docker: true
install_nvidia_container_toolkit: true
install_anaconda: true
install_pytorch: true
install_cuda_python: true

conda_env_name: "ml"
conda_env_python: "3.10"
conda_extra_conda_packages:
  - spyder
  - spyder-kernels
conda_pip_packages:
  - datasets
  - diffusers==0.25.0
  - transformers
  - accelerate
